version: '3.3'
volumes:
  site:
    driver: local
  data:
    driver: local
services:
   wordpress:
        build:
            context: ./wordpress
            dockerfile: Dockerfile
        image: nitin2174/wordpress:latest
        links:
            - mysql
        restart: always
        container_name: wordpress
        ports:
            - "10127:80"
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            MYSQL_PORT_3306_TCP: 10126
        depends_on:
            - mysql
        volumes:
            - site:/var/www/html
   mysql:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        image: nitin2174/mysql:5.7
        restart: unless-stopped
        hostname: mysql
        #command: --default-authentication-plugin=mysql_native_password
        container_name: ${MYSQL_HOST}
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "10126:3306"
        volumes:
            - data:/var/lib/mysql

   jenkins:
        build:
            context: ./jenkins
            dockerfile: Dockerfile
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        container_name: ${JENKINS_HOST}
        ports:
            - "10125:8080"
            - "50000:50000"
        volumes:
            - ./jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
